var simplemaps_usmap_mapdata = {
  main_settings: {
    //General settings
    width: "responsive", //or 'responsive'
    background_color: "#FFFFFF",
    background_transparent: "yes",
    popups: "detect",

    //State defaults
    state_description: "State description",
    state_color: "#88A4BC",
    state_hover_color: "#3B729F",
    // state_url: "https://simplemaps.com",
    border_size: 1.5,
    border_color: "#ffffff",
    all_states_inactive: "no",
    all_states_zoomable: "no",

    //Location defaults
    location_description: "Location description",
    location_color: "#FF0067",
    location_opacity: 0.8,
    location_hover_opacity: 1,
    location_url: "",
    location_size: 25,
    location_type: "square",
    location_border_color: "#FFFFFF",
    location_border: 2,
    location_hover_border: 2.5,
    all_locations_inactive: "no",
    all_locations_hidden: "no",

    //Label defaults
    label_color: "#ffffff",
    label_hover_color: "#ffffff",
    label_size: 22,
    label_font: "Arial",
    hide_labels: "no",

    //Zoom settings
    manual_zoom: "yes",
    back_image: "no",
    arrow_box: "no",
    navigation_size: "40",
    navigation_color: "#f7f7f7",
    navigation_border_color: "#636363",
    initial_back: "no",
    initial_zoom: -1,
    initial_zoom_solo: "no",
    region_opacity: 1,
    region_hover_opacity: 0.6,
    zoom_out_incrementally: "yes",
    zoom_percentage: 0.99,
    zoom_time: 0.5,

    //Popup settings
    popup_color: "white",
    popup_opacity: 0.9,
    popup_shadow: 1,
    popup_corners: 5,
    popup_font: "12px/1.5 Verdana, Arial, Helvetica, sans-serif",
    popup_nocss: "no",

    //Advanced settings
    div: "map",
    auto_load: "yes",
    rotate: "0",
    url_new_tab: "yes",
    images_directory: "default",
    import_labels: "no",
    fade_time: 0.1,
    link_text: "View Website",
  },
  state_specific: {},
  locations: {
    0: {
      name: "New York",
      lat: 40.71,
      lng: -74,
      description: "default",
      color: "default",
      url: "default",
      type: "default",
      size: "default",
    },
    1: {
      name: "Anchorage",
      lat: 61.2180556,
      lng: -149.9002778,
      color: "default",
      type: "circle",
    },
  },
  labels: {
    NH: {
      parent_id: "NH",
      x: "932",
      y: "183",
      pill: "yes",
      width: 45,
      display: "all",
    },
    VT: {
      parent_id: "VT",
      x: "883",
      y: "243",
      pill: "yes",
      width: 45,
      display: "all",
    },
    RI: {
      parent_id: "RI",
      x: "932",
      y: "273",
      pill: "yes",
      width: 45,
      display: "all",
    },
    NJ: {
      parent_id: "NJ",
      x: "883",
      y: "273",
      pill: "yes",
      width: 45,
      display: "all",
    },
    DE: {
      parent_id: "DE",
      x: "883",
      y: "303",
      pill: "yes",
      width: 45,
      display: "all",
    },
    MD: {
      parent_id: "MD",
      x: "932",
      y: "303",
      pill: "yes",
      width: 45,
      display: "all",
    },
    DC: {
      parent_id: "DC",
      x: "884",
      y: "332",
      pill: "yes",
      width: 45,
      display: "all",
    },
    MA: {
      parent_id: "MA",
      x: "932",
      y: "213",
      pill: "yes",
      width: 45,
      display: "all",
    },
    CT: {
      parent_id: "CT",
      x: "932",
      y: "243",
      pill: "yes",
      width: 45,
      display: "all",
    },
    HI: {
      parent_id: "HI",
      x: 305,
      y: 565,
      pill: "yes",
    },
    AK: {
      parent_id: "AK",
      x: "113",
      y: "495",
    },
    FL: {
      parent_id: "FL",
      x: "773",
      y: "510",
    },
    ME: {
      parent_id: "ME",
      x: "893",
      y: "85",
    },
    NY: {
      parent_id: "NY",
      x: "815",
      y: "158",
    },
    PA: {
      parent_id: "PA",
      x: "786",
      y: "210",
    },
    VA: {
      parent_id: "VA",
      x: "790",
      y: "282",
    },
    WV: {
      parent_id: "WV",
      x: "744",
      y: "270",
    },
    OH: {
      parent_id: "OH",
      x: "700",
      y: "240",
    },
    IN: {
      parent_id: "IN",
      x: "650",
      y: "250",
    },
    IL: {
      parent_id: "IL",
      x: "600",
      y: "250",
    },
    WI: {
      parent_id: "WI",
      x: "575",
      y: "155",
    },
    NC: {
      parent_id: "NC",
      x: "784",
      y: "326",
    },
    TN: {
      parent_id: "TN",
      x: "655",
      y: "340",
    },
    AR: {
      parent_id: "AR",
      x: "548",
      y: "368",
    },
    MO: {
      parent_id: "MO",
      x: "548",
      y: "293",
    },
    GA: {
      parent_id: "GA",
      x: "718",
      y: "405",
    },
    SC: {
      parent_id: "SC",
      x: "760",
      y: "371",
    },
    KY: {
      parent_id: "KY",
      x: "680",
      y: "300",
    },
    AL: {
      parent_id: "AL",
      x: "655",
      y: "405",
    },
    LA: {
      parent_id: "LA",
      x: "550",
      y: "435",
    },
    MS: {
      parent_id: "MS",
      x: "600",
      y: "405",
    },
    IA: {
      parent_id: "IA",
      x: "525",
      y: "210",
    },
    MN: {
      parent_id: "MN",
      x: "506",
      y: "124",
    },
    OK: {
      parent_id: "OK",
      x: "460",
      y: "360",
    },
    TX: {
      parent_id: "TX",
      x: "425",
      y: "435",
    },
    NM: {
      parent_id: "NM",
      x: "305",
      y: "365",
    },
    KS: {
      parent_id: "KS",
      x: "445",
      y: "290",
    },
    NE: {
      parent_id: "NE",
      x: "420",
      y: "225",
    },
    SD: {
      parent_id: "SD",
      x: "413",
      y: "160",
    },
    ND: {
      parent_id: "ND",
      x: "416",
      y: "96",
    },
    WY: {
      parent_id: "WY",
      x: "300",
      y: "180",
    },
    MT: {
      parent_id: "MT",
      x: "280",
      y: "95",
    },
    CO: {
      parent_id: "CO",
      x: "320",
      y: "275",
    },
    UT: {
      parent_id: "UT",
      x: "223",
      y: "260",
    },
    AZ: {
      parent_id: "AZ",
      x: "205",
      y: "360",
    },
    NV: {
      parent_id: "NV",
      x: "140",
      y: "235",
    },
    OR: {
      parent_id: "OR",
      x: "100",
      y: "120",
    },
    WA: {
      parent_id: "WA",
      x: "130",
      y: "55",
    },
    ID: {
      parent_id: "ID",
      x: "200",
      y: "150",
    },
    CA: {
      parent_id: "CA",
      x: "79",
      y: "285",
    },
    MI: {
      parent_id: "MI",
      x: "663",
      y: "185",
    },
    PR: {
      parent_id: "PR",
      x: "620",
      y: "545",
    },
    GU: {
      parent_id: "GU",
      x: "550",
      y: "540",
    },
    VI: {
      parent_id: "VI",
      x: "680",
      y: "519",
    },
    MP: {
      parent_id: "MP",
      x: "570",
      y: "575",
    },
    AS: {
      parent_id: "AS",
      x: "665",
      y: "580",
    },
  },
};

// Map settings to call showStateData on click
simplemaps_usmap_mapdata.state_specific = {
  HI: {
    name: "Hawaii",
    description: "Click for data",
    color: "#FF0000",
    hover_color: "#FF6347",
    url: "javascript:showStateData('HI')",
  },
  AK: {
    name: "Alaska",
    description: "Click for data",
    color: "#FF7F50",
    hover_color: "#CD5C5C",
    url: "javascript:showStateData('AK')",
  },
  FL: {
    name: "Florida",
    description: "Click for data",
    color: "#F0A30A",
    hover_color: "#FBD456",
    url: "javascript:showStateData('FL')",
  },
  NH: {
    name: "New Hampshire",
    description: "Click for data",
    color: "#FF8C00",
    hover_color: "#FFB347",
    url: "javascript:showStateData('NH')",
  },
  VT: {
    name: "Vermont",
    description: "Click for data",
    color: "#E9967A",
    hover_color: "#FFD700",
    url: "javascript:showStateData('VT')",
  },
  ME: {
    name: "Maine",
    description: "Click for data",
    color: "#FFFF00",
    hover_color: "#FFFACD",
    url: "javascript:showStateData('ME')",
  },
  RI: {
    name: "Rhode Island",
    description: "Click for data",
    color: "#EEE8AA",
    hover_color: "#F0E68C",
    url: "javascript:showStateData('RI')",
  },
  NY: {
    name: "New York",
    description: "Click for data",
    color: "#00ABA9",
    hover_color: "#1BA1E2",
    url: "javascript:showStateData('NY')",
  },
  PA: {
    name: "Pennsylvania",
    description: "Click for data",
    color: "#7FFF00",
    hover_color: "#32CD32",
    url: "javascript:showStateData('PA')",
  },
  NJ: {
    name: "New Jersey",
    description: "Click for data",
    color: "#00FF00",
    hover_color: "#0000FF",
    url: "javascript:showStateData('NJ')",
  },
  DE: {
    name: "Delaware",
    description: "Click for data",
    color: "#1E90FF",
    hover_color: "#87CEEB",
    url: "javascript:showStateData('DE')",
  },
  MD: {
    name: "Maryland",
    description: "Click for data",
    color: "#4682B4",
    hover_color: "#5F9EA0",
    url: "javascript:showStateData('MD')",
  },
  VA: {
    name: "Virginia",
    description: "Click for data",
    color: "#800080",
    hover_color: "#8A2BE2",
    url: "javascript:showStateData('VA')",
  },
  WV: {
    name: "West Virginia",
    description: "Click for data",
    color: "#9370DB",
    hover_color: "#BA55D3",
    url: "javascript:showStateData('WV')",
  },
  OH: {
    name: "Ohio",
    description: "Click for data",
    color: "#DDA0DD",
    hover_color: "#FF69B4",
    url: "javascript:showStateData('OH')",
  },
  IN: {
    name: "Indiana",
    description: "Click for data",
    color: "#FF1493",
    hover_color: "#FFB6C1",
    url: "javascript:showStateData('IN')",
  },
  IL: {
    name: "Illinois",
    description: "Click for data",
    color: "#FFC0CB",
    hover_color: "#DB7093",
    url: "javascript:showStateData('IL')",
  },
  CT: {
    name: "Connecticut",
    description: "Click for data",
    color: "#A52A2A",
    hover_color: "#8B4513",
    url: "javascript:showStateData('CT')",
  },
  WI: {
    name: "Wisconsin",
    description: "Click for data",
    color: "#D2691E",
    hover_color: "#F4A460",
    url: "javascript:showStateData('WI')",
  },
  NC: {
    name: "North Carolina",
    description: "Click for data",
    color: "#DEB887",
    hover_color: "#808080",
    url: "javascript:showStateData('NC')",
  },
  DC: {
    name: "District of Columbia",
    description: "Click for data",
    color: "#A9A9A9",
    hover_color: "#D3D3D3",
    url: "javascript:showStateData('DC')",
  },
  MA: {
    name: "Massachusetts",
    description: "Click for data",
    color: "#C0C0C0",
    hover_color: "#696969",
    url: "javascript:showStateData('MA')",
  },
  TN: {
    name: "Tennessee",
    description: "Click for data",
    color: "#00CED1",
    hover_color: "#40E0D0",
    url: "javascript:showStateData('TN')",
  },
  AR: {
    name: "Arkansas",
    description: "Click for data",
    color: "#48D1CC",
    hover_color: "#AFEEEE",
    url: "javascript:showStateData('AR')",
  },
  MO: {
    name: "Missouri",
    description: "Click for data",
    color: "#B0E0E6",
    hover_color: "#FFFFFF",
    url: "javascript:showStateData('MO')",
  },
  GA: {
    name: "Georgia",
    description: "Click for data",
    color: "#FFFAFA",
    hover_color: "#F0FFF0",
    url: "javascript:showStateData('GA')",
  },
  SC: {
    name: "South Carolina",
    description: "Click for data",
    color: "#F5FFFA",
    hover_color: "#F8F8FF",
    url: "javascript:showStateData('SC')",
  },
  KY: {
    name: "Kentucky",
    description: "Click for data",
    color: "#FF0000",
    hover_color: "#FF6347",
    url: "javascript:showStateData('KY')",
  },
  AL: {
    name: "Alabama",
    description: "Click for data",
    color: "#FF7F50",
    hover_color: "#CD5C5C",
    url: "javascript:showStateData('AL')",
  },
  LA: {
    name: "Louisiana",
    description: "Click for data",
    color: "#DC143C",
    hover_color: "#FF4500",
    url: "javascript:showStateData('LA')",
  },
  MS: {
    name: "Mississippi",
    description: "Click for data",
    color: "#FF8C00",
    hover_color: "#FFB347",
    url: "javascript:showStateData('MS')",
  },
  IA: {
    name: "Iowa",
    description: "Click for data",
    color: "#E9967A",
    hover_color: "#FFD700",
    url: "javascript:showStateData('IA')",
  },
  MN: {
    name: "Minnesota",
    description: "Click for data",
    color: "#FFFF00",
    hover_color: "#FFFACD",
    url: "javascript:showStateData('MN')",
  },
  OK: {
    name: "Oklahoma",
    description: "Click for data",
    color: "#EEE8AA",
    hover_color: "#F0E68C",
    url: "javascript:showStateData('OK')",
  },
  TX: {
    name: "Texas",
    description: "Click for data",
    color: "#008000",
    hover_color: "#ADFF2F",
    url: "javascript:showStateData('TX')",
  },
  NM: {
    name: "New Mexico",
    description: "Click for data",
    color: "#7FFF00",
    hover_color: "#32CD32",
    url: "javascript:showStateData('NM')",
  },
  KS: {
    name: "Kansas",
    description: "Click for data",
    color: "#00FF00",
    hover_color: "#0000FF",
    url: "javascript:showStateData('KS')",
  },
  NE: {
    name: "Nebraska",
    description: "Click for data",
    color: "#1E90FF",
    hover_color: "#87CEEB",
    url: "javascript:showStateData('NE')",
  },
  SD: {
    name: "South Dakota",
    description: "Click for data",
    color: "#4682B4",
    hover_color: "#5F9EA0",
    url: "javascript:showStateData('SD')",
  },
  ND: {
    name: "North Dakota",
    description: "Click for data",
    color: "#800080",
    hover_color: "#8A2BE2",
    url: "javascript:showStateData('ND')",
  },
  WY: {
    name: "Wyoming",
    description: "Click for data",
    color: "#9370DB",
    hover_color: "#BA55D3",
    url: "javascript:showStateData('WY')",
  },
  MT: {
    name: "Montana",
    description: "Click for data",
    color: "#DDA0DD",
    hover_color: "#FF69B4",
    url: "javascript:showStateData('MT')",
  },
  CO: {
    name: "Colorado",
    description: "Click for data",
    color: "#FF1493",
    hover_color: "#FFB6C1",
    url: "javascript:showStateData('CO')",
  },
  UT: {
    name: "Utah",
    description: "Click for data",
    color: "#FFC0CB",
    hover_color: "#DB7093",
    url: "javascript:showStateData('UT')",
  },
  AZ: {
    name: "Arizona",
    description: "Click for data",
    color: "#A52A2A",
    hover_color: "#8B4513",
    url: "javascript:showStateData('AZ')",
  },
  WA: {
    name: "Washington",
    description: "default",
    color: "#A9A9A9",
    hover_color: "#D3D3D3",
    url: "javascript:showStateData('WA')",
  },
  OR: {
    name: "Oregon",
    description: "default",
    color: "#DEB887",
    hover_color: "#808080",
    url: "javascript:showStateData('OR')",
  },
  ID: {
    name: "Idaho",
    description: "default",
    color: "#48D1CC",
    hover_color: "#AFEEEE",
    url: "javascript:showStateData('ID')",
  },
  NV: {
    name: "Nevada",
    description: "default",
    color: "#D2691E",
    hover_color: "#F4A460",
    url: "javascript:showStateData('NV')",
  },
  CA: {
    name: "California",
    description: "default",
    color: "#C0C0C0",
    hover_color: "#696969",
    url: "javascript:showStateData('CA')",
  },
};
